INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Box', 1, 194, 0);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Carton', 1, 195, 1);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Dozen', 1, 196, 2);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Each', 1, 197, 3);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Hours', 1, 198, 4);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Impressions', 1, 199, 5);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Lb', 1, 200, 6);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('M', 1, 201, 7);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Pack', 1, 202, 8);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Pages', 1, 203, 9);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Pieces', 1, 204, 10);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Quantity', 1, 205, 11);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Reams', 1, 206, 12);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Sheet', 1, 207, 13);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Spiral Binder', 1, 208, 14);
INSERT INTO crm_shinybesthk_com.vtiger_usageunit (usageunit, presence, picklist_valueid, sortorderid) VALUES ('Sq Ft', 1, 209, 15);