INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (1, 6, 4, 'get_contacts', 1, 'Contacts', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (2, 6, 2, 'get_opportunities', 2, 'Potentials', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (3, 6, 20, 'get_quotes', 3, 'Quotes', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (4, 6, 22, 'get_salesorder', 4, 'Sales Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (5, 6, 23, 'get_invoices', 5, 'Invoice', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (6, 6, 9, 'get_activities', 6, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (7, 6, 10, 'get_emails', 7, 'Emails', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (8, 6, 9, 'get_history', 8, 'Activity History', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (9, 6, 8, 'get_attachments', 9, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (10, 6, 13, 'get_tickets', 10, 'HelpDesk', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (11, 6, 14, 'get_products', 11, 'Products', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (12, 7, 9, 'get_activities', 1, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (13, 7, 10, 'get_emails', 2, 'Emails', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (14, 7, 9, 'get_history', 3, 'Activity History', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (15, 7, 8, 'get_attachments', 4, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (16, 7, 14, 'get_products', 5, 'Products', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (17, 7, 26, 'get_campaigns', 6, 'Campaigns', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (18, 4, 2, 'get_opportunities', 1, 'Potentials', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (19, 4, 9, 'get_activities', 2, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (20, 4, 10, 'get_emails', 3, 'Emails', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (21, 4, 13, 'get_tickets', 4, 'HelpDesk', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (22, 4, 20, 'get_quotes', 5, 'Quotes', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (23, 4, 21, 'get_purchase_orders', 6, 'Purchase Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (24, 4, 22, 'get_salesorder', 7, 'Sales Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (25, 4, 14, 'get_products', 8, 'Products', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (26, 4, 9, 'get_history', 9, 'Activity History', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (27, 4, 8, 'get_attachments', 10, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (28, 4, 26, 'get_campaigns', 11, 'Campaigns', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (29, 4, 23, 'get_invoices', 12, 'Invoice', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (30, 2, 9, 'get_activities', 1, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (31, 2, 4, 'get_contacts', 2, 'Contacts', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (32, 2, 14, 'get_products', 3, 'Products', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (33, 2, 0, 'get_stage_history', 4, 'Sales Stage History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (34, 2, 8, 'get_attachments', 5, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (35, 2, 20, 'get_Quotes', 6, 'Quotes', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (36, 2, 22, 'get_salesorder', 7, 'Sales Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (37, 2, 9, 'get_history', 8, 'Activity History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (38, 14, 13, 'get_tickets', 1, 'HelpDesk', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (39, 14, 8, 'get_attachments', 3, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (40, 14, 20, 'get_quotes', 4, 'Quotes', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (41, 14, 21, 'get_purchase_orders', 5, 'Purchase Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (42, 14, 22, 'get_salesorder', 6, 'Sales Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (43, 14, 23, 'get_invoices', 7, 'Invoice', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (44, 14, 19, 'get_product_pricebooks', 8, 'PriceBooks', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (45, 14, 7, 'get_leads', 9, 'Leads', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (46, 14, 6, 'get_accounts', 10, 'Accounts', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (47, 14, 4, 'get_contacts', 11, 'Contacts', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (48, 14, 2, 'get_opportunities', 12, 'Potentials', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (49, 14, 14, 'get_products', 13, 'Product Bundles', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (50, 14, 14, 'get_parent_products', 14, 'Parent Product', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (51, 10, 4, 'get_contacts', 1, 'Contacts', 0, 'select,bulkmail');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (52, 10, 0, 'get_users', 2, 'Users', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (53, 10, 8, 'get_attachments', 3, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (54, 13, 9, 'get_activities', 1, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (55, 13, 8, 'get_attachments', 2, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (56, 13, 0, 'get_ticket_history', 3, 'Ticket History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (57, 13, 9, 'get_history', 4, 'Activity History', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (58, 19, 14, 'get_pricebook_products', 2, 'Products', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (59, 18, 14, 'get_products', 1, 'Products', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (60, 18, 21, 'get_purchase_orders', 2, 'Purchase Order', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (61, 18, 4, 'get_contacts', 3, 'Contacts', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (62, 18, 10, 'get_emails', 4, 'Emails', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (63, 20, 22, 'get_salesorder', 1, 'Sales Order', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (64, 20, 9, 'get_activities', 2, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (65, 20, 8, 'get_attachments', 3, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (66, 20, 9, 'get_history', 4, 'Activity History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (67, 20, 0, 'get_quotestagehistory', 5, 'Quote Stage History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (68, 21, 9, 'get_activities', 1, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (69, 21, 8, 'get_attachments', 2, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (70, 21, 9, 'get_history', 3, 'Activity History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (71, 21, 0, 'get_postatushistory', 4, 'PurchaseOrder Status History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (72, 22, 9, 'get_activities', 1, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (73, 22, 8, 'get_attachments', 2, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (74, 22, 23, 'get_invoices', 3, 'Invoice', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (75, 22, 9, 'get_history', 4, 'Activity History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (76, 22, 0, 'get_sostatushistory', 5, 'SalesOrder Status History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (77, 23, 9, 'get_activities', 1, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (78, 23, 8, 'get_attachments', 2, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (79, 23, 9, 'get_history', 3, 'Activity History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (80, 23, 0, 'get_invoicestatushistory', 4, 'Invoice Status History', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (81, 9, 0, 'get_users', 1, 'Users', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (82, 9, 4, 'get_contacts', 2, 'Contacts', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (83, 26, 4, 'get_contacts', 1, 'Contacts', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (84, 26, 7, 'get_leads', 2, 'Leads', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (85, 26, 2, 'get_opportunities', 3, 'Potentials', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (86, 26, 9, 'get_activities', 4, 'Activities', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (87, 6, 26, 'get_campaigns', 13, 'Campaigns', 0, 'select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (88, 26, 6, 'get_accounts', 5, 'Accounts', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (89, 15, 8, 'get_attachments', 1, 'Documents', 0, 'add,select');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (90, 30, 13, 'get_related_list', 1, 'HelpDesk', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (91, 30, 20, 'get_quotes', 2, 'Quotes', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (92, 30, 21, 'get_purchase_orders', 3, 'Purchase Order', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (93, 30, 22, 'get_salesorder', 4, 'Sales Order', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (94, 30, 23, 'get_invoices', 5, 'Invoice', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (95, 30, 19, 'get_service_pricebooks', 6, 'PriceBooks', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (96, 30, 7, 'get_related_list', 7, 'Leads', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (97, 30, 6, 'get_related_list', 8, 'Accounts', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (98, 30, 4, 'get_related_list', 9, 'Contacts', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (99, 30, 2, 'get_related_list', 10, 'Potentials', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (100, 30, 8, 'get_attachments', 11, 'Documents', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (101, 13, 30, 'get_related_list', 5, 'Services', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (102, 7, 30, 'get_related_list', 7, 'Services', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (103, 6, 30, 'get_related_list', 14, 'Services', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (104, 4, 30, 'get_related_list', 13, 'Services', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (105, 2, 30, 'get_related_list', 9, 'Services', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (106, 19, 30, 'get_pricebook_services', 3, 'Services', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (107, 33, 13, 'get_related_list', 1, 'Service Requests', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (108, 33, 8, 'get_attachments', 2, 'Documents', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (109, 6, 33, 'get_dependents_list', 15, 'Service Contracts', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (110, 4, 33, 'get_dependents_list', 14, 'Service Contracts', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (111, 13, 33, 'get_related_list', 6, 'Service Contracts', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (112, 4, 35, 'get_dependents_list', 15, 'PBXManager', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (113, 7, 35, 'get_dependents_list', 8, 'PBXManager', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (114, 6, 35, 'get_dependents_list', 16, 'PBXManager', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (115, 39, 6, 'get_related_list', 1, 'Accounts', 0, ' ');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (116, 39, 4, 'get_related_list', 2, 'Contacts', 0, ' ');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (117, 39, 7, 'get_related_list', 3, 'Leads', 0, ' ');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (124, 6, 46, 'get_dependents_list', 17, 'Projects', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (125, 4, 46, 'get_dependents_list', 16, 'Projects', 0, 'add');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (126, 13, 46, 'get_related_list', 7, 'Projects', 0, 'SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (127, 47, 13, 'get_related_list', 1, 'HelpDesk', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (128, 47, 8, 'get_attachments', 2, 'Documents', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (129, 6, 47, 'get_dependents_list', 18, 'Assets', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (130, 14, 47, 'get_dependents_list', 15, 'Assets', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (131, 23, 47, 'get_dependents_list', 5, 'Assets', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (132, 45, 8, 'get_attachments', 1, 'Documents', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (133, 46, 45, 'get_dependents_list', 1, 'Project Tasks', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (134, 46, 44, 'get_dependents_list', 2, 'Project Milestones', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (135, 46, 8, 'get_attachments', 3, 'Documents', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (136, 46, 13, 'get_related_list', 4, 'HelpDesk', 0, 'ADD,SELECT');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (137, 46, 0, 'get_gantt_chart', 5, 'Charts', 0, '');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (138, 4, 47, 'get_dependents_list', 17, 'Assets', 0, 'ADD');
INSERT INTO crm_shinybesthk_com.vtiger_relatedlists (relation_id, tabid, related_tabid, name, sequence, label, presence, actions) VALUES (139, 4, 18, 'get_vendors', 18, 'Vendors', 0, 'SELECT');