INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Albania, Leke', 'ALL', 'Lek');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Argentina, Pesos', 'ARS', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Aruba, Guilders', 'AWG', 'ƒ');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Australia, Dollars', 'AUD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Azerbaijan, New Manats', 'AZN', 'ман');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Bahamas, Dollars', 'BSD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Bahrain, Dinar', 'BHD', 'BD');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Barbados, Dollars', 'BBD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Belarus, Rubles', 'BYR', 'p.');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Belize, Dollars', 'BZD', 'BZ$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Bermuda, Dollars', 'BMD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Bolivia, Bolivianos', 'BOB', '$b');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('China, Yuan Renminbi', 'CNY', '¥');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Convertible Marka', 'BAM', 'KM');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Botswana, Pulas', 'BWP', 'P');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Bulgaria, Leva', 'BGN', 'лв');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Brazil, Reais', 'BRL', 'R$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Great Britain Pounds', 'GBP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Brunei Darussalam, Dollars', 'BND', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Canada, Dollars', 'CAD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Cayman Islands, Dollars', 'KYD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Chile, Pesos', 'CLP', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Colombia, Pesos', 'COP', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Costa Rica, Colón', 'CRC', '₡');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Croatia, Kuna', 'HRK', 'kn');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Cuba, Pesos', 'CUP', '₱');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Czech Republic, Koruny', 'CZK', 'Kč');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Cyprus, Pounds', 'CYP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Denmark, Kroner', 'DKK', 'kr');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Dominican Republic, Pesos', 'DOP', 'RD$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('East Caribbean, Dollars', 'XCD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Egypt, Pounds', 'EGP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('El Salvador, Colón', 'SVC', '₡');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('England, Pounds', 'GBP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Estonia, Krooni', 'EEK', 'kr');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Euro', 'EUR', '€');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Falkland Islands, Pounds', 'FKP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Fiji, Dollars', 'FJD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Ghana, Cedis', 'GHC', '¢');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Gibraltar, Pounds', 'GIP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Guatemala, Quetzales', 'GTQ', 'Q');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Guernsey, Pounds', 'GGP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Guyana, Dollars', 'GYD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Honduras, Lempiras', 'HNL', 'L');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Hong Kong, Dollars', 'HKD', 'HK$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Hungary, Forint', 'HUF', 'Ft');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Iceland, Krona', 'ISK', 'kr');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('India, Rupees', 'INR', '₹');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Indonesia, Rupiahs', 'IDR', 'Rp');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Iran, Rials', 'IRR', '﷼');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Isle of Man, Pounds', 'IMP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Israel, New Shekels', 'ILS', '₪');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Jamaica, Dollars', 'JMD', 'J$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Japan, Yen', 'JPY', '¥');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Jersey, Pounds', 'JEP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Jordan, Dinar', 'JOD', 'JOD');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Kazakhstan, Tenge', 'KZT', '〒');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Kenya, Shilling', 'KES', 'KES');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Korea (North), Won', 'KPW', '₩');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Korea (South), Won', 'KRW', '₩');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Kuwait, Dinar', 'KWD', 'KWD');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Kyrgyzstan, Soms', 'KGS', 'лв');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Laos, Kips', 'LAK', '₭');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Latvia, Lati', 'LVL', 'Ls');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Lebanon, Pounds', 'LBP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Liberia, Dollars', 'LRD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Switzerland Francs', 'CHF', 'CHF');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Lithuania, Litai', 'LTL', 'Lt');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('MADAGASCAR, Malagasy Ariary', 'MGA', 'MGA');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Macedonia, Denars', 'MKD', 'ден');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Malaysia, Ringgits', 'MYR', 'RM');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Malta, Liri', 'MTL', '₤');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Mauritius, Rupees', 'MUR', '₨');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Mexico, Pesos', 'MXN', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Mongolia, Tugriks', 'MNT', '₮');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Mozambique, Meticais', 'MZN', 'MT');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Namibia, Dollars', 'NAD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Nepal, Rupees', 'NPR', '₨');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Netherlands Antilles, Guilders', 'ANG', 'ƒ');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('New Zealand, Dollars', 'NZD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Nicaragua, Cordobas', 'NIO', 'C$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Nigeria, Nairas', 'NGN', '₦');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('North Korea, Won', 'KPW', '₩');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Norway, Krone', 'NOK', 'kr');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Oman, Rials', 'OMR', '﷼');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Pakistan, Rupees', 'PKR', '₨');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Panama, Balboa', 'PAB', 'B/.');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Paraguay, Guarani', 'PYG', 'Gs');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Peru, Nuevos Soles', 'PEN', 'S/.');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Philippines, Pesos', 'PHP', 'Php');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Poland, Zlotych', 'PLN', 'zł');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Qatar, Rials', 'QAR', '﷼');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Romania, New Lei', 'RON', 'lei');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Russia, Rubles', 'RUB', 'руб');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Saint Helena, Pounds', 'SHP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Saudi Arabia, Riyals', 'SAR', '﷼');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Serbia, Dinars', 'RSD', 'Дин.');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Seychelles, Rupees', 'SCR', '₨');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Singapore, Dollars', 'SGD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Solomon Islands, Dollars', 'SBD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Somalia, Shillings', 'SOS', 'S');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('South Africa, Rand', 'ZAR', 'R');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('South Korea, Won', 'KRW', '₩');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Sri Lanka, Rupees', 'LKR', '₨');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Sweden, Kronor', 'SEK', 'kr');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Switzerland, Francs', 'CHF', 'CHF');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Suriname, Dollars', 'SRD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Syria, Pounds', 'SYP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Taiwan, New Dollars', 'TWD', 'NT$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Thailand, Baht', 'THB', '฿');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Trinidad and Tobago, Dollars', 'TTD', 'TT$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Turkey, New Lira', 'TRY', 'YTL');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Turkey, Liras', 'TRL', '₤');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Tuvalu, Dollars', 'TVD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Ukraine, Hryvnia', 'UAH', '₴');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('United Arab Emirates, Dirham', 'AED', 'AED');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('United Kingdom, Pounds', 'GBP', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('United Republic of Tanzania, Shilling', 'TZS', 'TZS');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('USA, Dollars', 'USD', '$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Uruguay, Pesos', 'UYU', '$U');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Uzbekistan, Sums', 'UZS', 'лв');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Venezuela, Bolivares Fuertes', 'VEF', 'Bs');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Vietnam, Dong', 'VND', '₫');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Zambia, Kwacha', 'ZMK', 'ZMK');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Yemen, Rials', 'YER', '﷼');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Zimbabwe Dollars', 'ZWD', 'Z$');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Malawi, Kwacha', 'MWK', 'MK');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Tunisian, Dinar', 'TD', 'TD');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Moroccan, Dirham', 'MAD', 'DH');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Iraqi Dinar', 'IQD', 'ID');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Maldivian Ruffiya', 'MVR', 'MVR');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Ugandan Shilling', 'UGX', 'Sh');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Sudanese Pound', 'SDG', '£');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('CFA Franc BCEAO', 'XOF', 'CFA');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('CFA Franc BEAC', 'XAF', 'CFA');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Haiti, Gourde', 'HTG', 'G');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('Libya, Dinar', 'LYD', 'LYD');
INSERT INTO crm_shinybesthk_com.vtiger_currencies (currency_name, currency_code, currency_symbol) VALUES ('CFP Franc', 'XPF', 'F');