INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Conference', 1, 21, 1);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Webinar', 1, 22, 2);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Trade Show', 1, 23, 3);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Public Relations', 1, 24, 4);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Partners', 1, 25, 5);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Referral Program', 1, 26, 6);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Advertisement', 1, 27, 7);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Banner Ads', 1, 28, 8);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Direct Mail', 1, 29, 9);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Email', 1, 30, 10);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Telemarketing', 1, 31, 11);
INSERT INTO crm_shinybesthk_com.vtiger_campaigntype (campaigntype, presence, picklist_valueid, sortorderid) VALUES ('Others', 1, 32, 12);