INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Account and Contact Reports', 'Account and Contact Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Lead Reports', 'Lead Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Potential Reports', 'Potential Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Activity Reports', 'Activity Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('HelpDesk Reports', 'HelpDesk Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Product Reports', 'Product Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Quote Reports', 'Quote Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('PurchaseOrder Reports', 'PurchaseOrder Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Invoice Reports', 'Invoice Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('SalesOrder Reports', 'SalesOrder Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Campaign Reports', 'Campaign Reports', 'SAVED');
INSERT INTO crm_shinybesthk_com.vtiger_reportfolder (foldername, description, state) VALUES ('Email Reports', 'Email Reports', 'SAVED');