INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Attempted to Contact', 1, 112, 1);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Cold', 1, 113, 2);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Contact in Future', 1, 114, 3);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Contacted', 1, 115, 4);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Hot', 1, 116, 5);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Junk Lead', 1, 117, 6);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Lost Lead', 1, 118, 7);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Not Contacted', 1, 119, 8);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Pre Qualified', 1, 120, 9);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Qualified', 1, 121, 10);
INSERT INTO crm_shinybesthk_com.vtiger_leadstatus (leadstatus, presence, picklist_valueid, sortorderid) VALUES ('Warm', 1, 122, 11);