INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Administrator', 'Admin Profile', 0);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Profile', 'Profile Related to Sales', 0);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Support Profile', 'Profile Related to Support', 0);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Guest Profile', 'Guest Profile for Test Users', 0);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Vice President-E+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Manager-Aska+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Manager-Sampras+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Director-Kevin+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Manager-Dick+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Director- Henry+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Manager-Raymond+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Sales Manager-Jennifer+配置', null, 1);
INSERT INTO crm_shinybesthk_com.vtiger_profile (profilename, description, directly_related_to_role) VALUES ('Admin+配置', null, 1);