INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (6, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (11, '', '38 Wang Lee Street, Yuen Long Industrial Estate, 
Bright Future Pharmaceutical Centre, Yuen Long, N.T., Hong Kong', '', '', '', '', '', '', '', '', '38 Wang Lee Street, Yuen Long Industrial Estate, 
Bright Future Pharmaceutical Centre, Yuen Long, N.T., Hong Kong', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (18, '', '7/F, Cityplaza One, 1111 King''s Road', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (36, '', '2/F, Garment Centre', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (37, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (43, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (49, '', '1/F, Century Center, 44-46 Hung To road, Kwun Tong, HK', '', '', '', '', '', '', '', '', '1/F, Century Center, 44-46 Hung To road, Kwun Tong, HK', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (59, '', 'Room D, Block G, 15/K, Phrase 2, Kwai Shing Ind Building, 42-46 Tai Lin Pai RD, Kwai Chung, NT', '', '', '', '', '', '', '', '', 'Room D, Block G, 15/K, Phrase 2, Kwai Shing Ind Building, 42-46 Tai Lin Pai RD, Kwai Chung, NT', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (73, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (76, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (79, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (86, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (89, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (92, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (96, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (99, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (104, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (107, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (108, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (126, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (129, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (135, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (139, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (142, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (157, '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_contactaddress (contactaddressid, mailingcity, mailingstreet, mailingcountry, othercountry, mailingstate, mailingpobox, othercity, otherstate, mailingzip, otherzip, otherstreet, otherpobox) VALUES (158, '', '', '', '', '', '', '', '', '', '', '', '');