INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (1, 1, 'Default', 1, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (2, 2, 'Default', 1, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (3, 3, 'Default', 1, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (4, 4, 'Default', 1, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (5, 5, 'Default', 1, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (6, 6, 'Default', 1, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (7, 7, 'Default', 1, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (8, 8, 'Default', 1, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (9, 9, 'Default', 1, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (10, 10, 'Default', 1, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (11, 11, 'Default', 1, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (12, 12, 'Default', 1, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (13, 13, 'Default', 1, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (14, 14, 'Default', 1, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (15, 15, 'Tag Cloud', 1, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (16, 1, 'Default', 5, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (17, 2, 'Default', 5, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (18, 3, 'Default', 5, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (19, 4, 'Default', 5, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (20, 5, 'Default', 5, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (21, 6, 'Default', 5, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (22, 7, 'Default', 5, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (23, 8, 'Default', 5, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (24, 9, 'Default', 5, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (25, 10, 'Default', 5, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (26, 11, 'Default', 5, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (27, 12, 'Default', 5, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (28, 13, 'Default', 5, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (29, 14, 'Default', 5, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (30, 15, 'Tag Cloud', 5, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (31, 1, 'Default', 6, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (32, 2, 'Default', 6, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (33, 3, 'Default', 6, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (34, 4, 'Default', 6, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (35, 5, 'Default', 6, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (36, 6, 'Default', 6, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (37, 7, 'Default', 6, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (38, 8, 'Default', 6, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (39, 9, 'Default', 6, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (40, 10, 'Default', 6, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (41, 11, 'Default', 6, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (42, 12, 'Default', 6, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (43, 13, 'Default', 6, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (44, 14, 'Default', 6, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (45, 15, 'Tag Cloud', 6, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (76, 1, 'Default', 9, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (77, 2, 'Default', 9, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (78, 3, 'Default', 9, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (79, 4, 'Default', 9, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (80, 5, 'Default', 9, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (81, 6, 'Default', 9, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (82, 7, 'Default', 9, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (83, 8, 'Default', 9, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (84, 9, 'Default', 9, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (85, 10, 'Default', 9, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (86, 11, 'Default', 9, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (87, 12, 'Default', 9, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (88, 13, 'Default', 9, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (89, 14, 'Default', 9, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (90, 15, 'Tag Cloud', 9, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (136, 1, 'Default', 15, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (137, 2, 'Default', 15, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (138, 3, 'Default', 15, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (139, 4, 'Default', 15, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (140, 5, 'Default', 15, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (141, 6, 'Default', 15, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (142, 7, 'Default', 15, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (143, 8, 'Default', 15, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (144, 9, 'Default', 15, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (145, 10, 'Default', 15, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (146, 11, 'Default', 15, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (147, 12, 'Default', 15, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (148, 13, 'Default', 15, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (149, 14, 'Default', 15, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (150, 15, 'Tag Cloud', 15, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (151, 1, 'Default', 16, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (152, 2, 'Default', 16, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (153, 3, 'Default', 16, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (154, 4, 'Default', 16, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (155, 5, 'Default', 16, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (156, 6, 'Default', 16, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (157, 7, 'Default', 16, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (158, 8, 'Default', 16, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (159, 9, 'Default', 16, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (160, 10, 'Default', 16, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (161, 11, 'Default', 16, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (162, 12, 'Default', 16, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (163, 13, 'Default', 16, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (164, 14, 'Default', 16, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (165, 15, 'Tag Cloud', 16, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (181, 1, 'Default', 18, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (182, 2, 'Default', 18, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (183, 3, 'Default', 18, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (184, 4, 'Default', 18, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (185, 5, 'Default', 18, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (186, 6, 'Default', 18, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (187, 7, 'Default', 18, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (188, 8, 'Default', 18, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (189, 9, 'Default', 18, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (190, 10, 'Default', 18, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (191, 11, 'Default', 18, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (192, 12, 'Default', 18, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (193, 13, 'Default', 18, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (194, 14, 'Default', 18, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (195, 15, 'Tag Cloud', 18, 0, 'Tag Cloud');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (196, 1, 'Default', 19, 1, 'Top Accounts');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (197, 2, 'Default', 19, 1, 'Home Page Dashboard');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (198, 3, 'Default', 19, 1, 'Top Potentials');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (199, 4, 'Default', 19, 1, 'Top Quotes');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (200, 5, 'Default', 19, 1, 'Key Metrics');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (201, 6, 'Default', 19, 1, 'Top Trouble Tickets');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (202, 7, 'Default', 19, 1, 'Upcoming Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (203, 8, 'Default', 19, 1, 'My Group Allocation');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (204, 9, 'Default', 19, 1, 'Top Sales Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (205, 10, 'Default', 19, 1, 'Top Invoices');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (206, 11, 'Default', 19, 1, 'My New Leads');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (207, 12, 'Default', 19, 1, 'Top Purchase Orders');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (208, 13, 'Default', 19, 1, 'Pending Activities');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (209, 14, 'Default', 19, 1, 'My Recent FAQs');
INSERT INTO crm_shinybesthk_com.vtiger_homestuff (stuffid, stuffsequence, stufftype, userid, visible, stufftitle) VALUES (210, 15, 'Tag Cloud', 19, 0, 'Tag Cloud');