INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (7, '', '', '', '', 'Level 2, The Long Beach Commercial Podium, 8 Hoi Fai Road, Kowloon, HK', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (10, '', '', '', '', '38 Wang Lee Street, Yuen Long Industrial Estate, 
Bright Future Pharmaceutical Centre, Yuen Long, N.T., Hong Kong', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (19, '', '', '', '', '7/F, Cityplaza One, 1111 King''s Road', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (34, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (35, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (44, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (47, '', '', '', '', '1/F, Century Center, 44-46 Hung To road, Kwun Tong, HK', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (48, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (51, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (55, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (58, '', '', '', '', 'Room D, Block G, 15/K, Phrase 2, Kwai Shing Ind Building, 42-46 Tai Lin Pai RD, Kwai Chung, NT', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (61, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (63, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (66, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (72, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (75, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (78, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (87, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (90, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (93, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (95, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (98, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (101, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (103, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (106, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (109, '', '', 'Hong Kong', '', 'Rm 6, 6/F., Sun Fung Ctr.,
88 Kwok Shui Rd., Kwai Chung, N.T.', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (127, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (130, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (132, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (134, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (138, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (154, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (159, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (164, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (165, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (166, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountbillads (accountaddressid, bill_city, bill_code, bill_country, bill_state, bill_street, bill_pobox) VALUES (168, '', '', '', '', '', '');