INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (1, 'All', 1, 0, 'Leads', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (2, 'Hot Leads', 0, 1, 'Leads', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (3, 'This Month Leads', 0, 0, 'Leads', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (4, 'All', 1, 0, 'Accounts', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (5, 'Prospect Accounts', 0, 1, 'Accounts', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (6, 'New This Week', 0, 0, 'Accounts', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (7, 'All', 1, 0, 'Contacts', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (8, 'Contacts Address', 0, 0, 'Contacts', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (9, 'Todays Birthday', 0, 0, 'Contacts', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (10, 'All', 1, 0, 'Potentials', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (11, 'Potentials Won', 0, 1, 'Potentials', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (12, 'Prospecting', 0, 0, 'Potentials', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (13, 'All', 1, 0, 'HelpDesk', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (14, 'Open Tickets', 0, 1, 'HelpDesk', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (15, 'High Prioriy Tickets', 0, 0, 'HelpDesk', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (16, 'All', 1, 0, 'Quotes', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (17, 'Open Quotes', 0, 1, 'Quotes', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (18, 'Rejected Quotes', 0, 0, 'Quotes', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (19, 'All', 1, 0, 'Calendar', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (20, 'All', 1, 0, 'Emails', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (21, 'All', 1, 0, 'Invoice', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (22, 'All', 1, 0, 'Documents', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (23, 'All', 1, 0, 'PriceBooks', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (24, 'All', 1, 0, 'Products', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (25, 'All', 1, 0, 'PurchaseOrder', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (26, 'All', 1, 0, 'SalesOrder', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (27, 'All', 1, 0, 'Vendors', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (28, 'All', 1, 0, 'Faq', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (29, 'All', 1, 0, 'Campaigns', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (30, 'All', 1, 0, 'Webmails', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (31, 'Drafted FAQ', 0, 0, 'Faq', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (32, 'Published FAQ', 0, 0, 'Faq', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (33, 'Open Purchase Orders', 0, 0, 'PurchaseOrder', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (34, 'Received Purchase Orders', 0, 0, 'PurchaseOrder', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (35, 'Open Invoices', 0, 0, 'Invoice', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (36, 'Paid Invoices', 0, 0, 'Invoice', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (37, 'Pending Sales Orders', 0, 0, 'SalesOrder', 3, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (38, 'All', 1, 0, 'Services', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (39, 'All', 1, 0, 'ServiceContracts', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (40, 'All', 1, 0, 'PBXManager', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (41, 'All', 0, 0, 'SMSNotifier', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (42, 'All', 0, 0, 'ModComments', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (46, 'All', 1, 0, 'Assets', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (47, 'All', 1, 0, 'ProjectMilestone', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (48, 'All', 1, 0, 'ProjectTask', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (49, 'All', 1, 0, 'Project', 0, 1);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (51, 'Sampras', 0, 0, 'Potentials', 1, 7);
INSERT INTO crm_shinybesthk_com.vtiger_customview (cvid, viewname, setdefault, setmetrics, entitytype, status, userid) VALUES (53, 'Chris', 0, 0, 'Potentials', 1, 8);