INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (7, '', '', '', '', '', 'Level 2, The Long Beach Commercial Podium, 8 Hoi Fai Road, Kowloon, HK');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (10, '', '', '', '', '', '38 Wang Lee Street, Yuen Long Industrial Estate, 
Bright Future Pharmaceutical Centre, Yuen Long, N.T., Hong Kong');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (19, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (34, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (35, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (44, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (47, '', '', '', '', '', '1/F, Century Center, 44-46 Hung To road, Kwun Tong, HK');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (48, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (51, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (55, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (58, '', '', '', '', '', 'Room D, Block G, 15/K, Phrase 2, Kwai Shing Ind Building, 42-46 Tai Lin Pai RD, Kwai Chung, NT');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (61, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (63, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (66, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (72, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (75, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (78, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (87, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (90, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (93, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (95, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (98, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (101, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (103, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (106, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (109, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (127, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (130, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (132, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (134, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (138, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (154, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (159, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (164, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (165, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (166, '', '', '', '', '', '');
INSERT INTO crm_shinybesthk_com.vtiger_accountshipads (accountaddressid, ship_city, ship_code, ship_country, ship_state, ship_pobox, ship_street) VALUES (168, '', '', '', '', '', '');